import { ExpertParameterConfig } from '@src/models/expert-parameter-config.ts';

export const BASE_PARAMETERS: ExpertParameterConfig[] = [
  { name: 'Inversion', value: 1, variable: true, min: 0, max: 1, step: 1 },
  { name: 'Base_Unit', value: 1, variable: false, min: 0, max: 1, step: 0 },
  { name: 'ATR_Period', value: 200, variable: false, min: 200, max: 2000, step: 1 },
  { name: 'TP_Distance', value: 3, variable: true, min: 1, max: 3, step: 1 },
  { name: 'SL_Ratio', value: 0, variable: false, min: 2, max: 20, step: 0.2 },
  { name: 'Break_Even_In_Percent', value: 0, variable: false, min: 0, max: 0, step: 0 },
  { name: 'TS_Start_In_Percent', value: 0, variable: false, min: 0, max: 0, step: 0 },
  { name: 'TS_Distance', value: 0, variable: false, min: 0, max: 0, step: 0 },
  { name: 'TS_Step', value: 1, variable: false, min: 0.1, max: 10, step: 1 },
  { name: 'SL_Move', value: 0, variable: false, min: 0, max: 1, step: 0 },
  { name: 'Distance_Between_Orders', value: 4, variable: true, min: 4, max: 8, step: 2 },
  { name: 'Distance_Between_Orders_Factor', value: 1, variable: false, min: 0.1, max: 10, step: 1 },
  { name: 'Trade_Direction', value: 3, variable: false, min: 0, max: 3, step: 1 },
  { name: 'Ini_Lot_Size_For_10k', value: 0.03, variable: true, min: 0.02, max: 0.06, step: 0.02 },
  { name: 'Use_Fixed_Lot_Size', value: 0, variable: false, min: 0, max: 1, step: 0 },
  { name: 'Ini_Risk_In_Percent', value: 0, variable: false, min: 0, max: 0, step: 0 },
  { name: 'Fixed_Grid_Size', value: 1, variable: false, min: 0, max: 1, step: 0 },
  { name: 'Recovery_Factor', value: 0, variable: false, min: 0, max: 0, step: 0 },
  { name: 'Grid_Recovery_Factor', value: 2, variable: false, min: 1.3, max: 2, step: 0.7 },
  { name: 'Grid_Recovery_Factor_Modifier', value: 1, variable: false, min: 0.1, max: 10, step: 1 },
  { name: 'Grid_Lot_Sum', value: 0, variable: false, min: 0, max: 0, step: 0 },
  { name: 'Grid_Special_Reaction', value: 0, variable: false, min: 1, max: 10, step: 0 },
  { name: 'Grid_Pause_Until_GSR', value: 0, variable: false, min: 0, max: 1, step: 0 },
  { name: 'Grid_Lot_Boost_On_GSR', value: 0, variable: false, min: 0, max: 0, step: 0 },
  { name: 'Grid_Result_Boost_On_GSR', value: 0, variable: false, min: 0, max: 0, step: 0 },
  { name: 'Smart_Loss_Management_On_DD', value: 0, variable: false, min: 0, max: 0, step: 0 },
  { name: 'Smart_Loss_Management_Mode', value: 0, variable: false, min: 0, max: 2, step: 0 },
  { name: 'Smart_Account_Protection_On_DD', value: 0, variable: false, min: 0, max: 0, step: 0 },
  { name: 'Close_All_Orders_On_DD', value: 0, variable: false, min: 0, max: 0, step: 0 },
  {
    name: 'Close_All_Orders_When_Profit_In_Percent',
    value: 0,
    variable: false,
    min: 0,
    max: 0,
    step: 0,
  },
  { name: 'Close_On_Common_TP', value: 1, variable: false, min: 0, max: 1, step: 0 },
  { name: 'Use_Common_SL', value: 0, variable: false, min: 0, max: 1, step: 0 },
  { name: 'Ajust_First_TP', value: 0, variable: false, min: 0, max: 1, step: 0 },
  { name: 'Min_TP_Move_In_Point', value: 10, variable: false, min: 10, max: 100, step: 1 },
  { name: 'Max_Risk_In_Percent', value: 0, variable: false, min: 0, max: 0, step: 0 },
  { name: 'Max_Lot_Size_For_10k', value: 0.3, variable: false, min: 0, max: 0, step: 0 },
  { name: 'Max_Opened_Orders_By_EA_Per_Size', value: 0, variable: false, min: 1, max: 10, step: 0 },
  { name: 'Max_Opened_Orders_By_EA', value: 0, variable: false, min: 1, max: 10, step: 0 },
  { name: 'Max_Opened_Orders', value: 0, variable: false, min: 1, max: 10, step: 0 },
  { name: 'Max_Symbols_In_Same_Time', value: 0, variable: false, min: 1, max: 10, step: 0 },
  { name: 'Max_Daily_DD_In_Percent', value: 0, variable: false, min: 0, max: 0, step: 0 },
  { name: 'Max_Daily_Loss', value: 0, variable: false, min: 0, max: 0, step: 0 },
  { name: 'Max_Daily_Profit_In_Percent', value: 0, variable: false, min: 0, max: 0, step: 0 },
  { name: 'Restart_Hour', value: 0, variable: false, min: 0, max: 86100, step: 0 },
  { name: 'Non_Trading_DD', value: 10, variable: false, min: 0, max: 0, step: 0 },
  { name: 'Stop_EA', value: 0, variable: false, min: 0, max: 1, step: 0 },
  { name: 'Old_Orders_Close_On_DD', value: 0, variable: false, min: 0, max: 0, step: 0 },
  { name: 'Max_Equity_Stop', value: 0, variable: false, min: 0, max: 0, step: 0 },
  { name: 'Min_Equity_Stop', value: 0, variable: false, min: 0, max: 0, step: 0 },
  { name: 'EA_Max_Win', value: 0, variable: false, min: 0, max: 0, step: 0 },
  { name: 'EA_Max_Loss', value: 0, variable: false, min: 0, max: 0, step: 0 },
  { name: 'EA_Monthly_Max_Win', value: 0, variable: false, min: 0, max: 0, step: 0 },
  { name: 'Trade_Max_Profit_In_Percent', value: 0, variable: false, min: 0, max: 0, step: 0 },
  { name: 'Trade_Max_Loss_In_Percent', value: 0, variable: false, min: 0, max: 0, step: 0 },
  { name: 'Slippage', value: 50, variable: false, min: 50, max: 500, step: 1 },
  { name: 'Max_Hours_Before_Break_Even', value: 0, variable: false, min: 0, max: 0, step: 0 },
  { name: 'Max_Hours_Before_Closing', value: 0, variable: false, min: 0, max: 0, step: 0 },
  { name: 'Min_Hours_Between_Trade', value: 0, variable: false, min: 0, max: 0, step: 0 },
  { name: 'Min_Hours_After_Loss', value: 0, variable: false, min: 0, max: 0, step: 0 },
  { name: 'Pause_Orders_On_Friday', value: 0, variable: false, min: 0, max: 1, step: 0 },
  { name: 'Pausing_Hour', value: 57600, variable: false, min: 0, max: 86100, step: 0 },
  { name: 'Close_Orders_On_Friday', value: 0, variable: false, min: 0, max: 1, step: 0 },
  { name: 'Closing_Hour', value: 57600, variable: false, min: 0, max: 86100, step: 0 },
  { name: 'Apply_Hour_Filter', value: 0, variable: false, min: 0, max: 1, step: 0 },
  { name: 'Start', value: 28800, variable: false, min: 0, max: 86100, step: 0 },
  { name: 'Stop', value: 57600, variable: false, min: 0, max: 86100, step: 0 },
  { name: 'Apply_Hour_Filter_Action', value: 1, variable: false, min: 0, max: 2, step: 1 },
  { name: 'Trade_Monday', value: 1, variable: false, min: 0, max: 1, step: 0 },
  { name: 'Trade_Tuesday', value: 1, variable: false, min: 0, max: 1, step: 0 },
  { name: 'Trade_Wednesday', value: 1, variable: false, min: 0, max: 1, step: 0 },
  { name: 'Trade_Thursday', value: 1, variable: false, min: 0, max: 1, step: 0 },
  { name: 'Trade_Friday', value: 1, variable: false, min: 0, max: 1, step: 0 },
  { name: 'Trade_Saturday', value: 1, variable: false, min: 0, max: 1, step: 0 },
  { name: 'Trade_Sunday', value: 1, variable: false, min: 0, max: 1, step: 0 },
  { name: 'Max_Amount_Of_First_Entries', value: 1, variable: false, min: 1, max: 10, step: 1 },
];
