import { ExpertAdvisor } from '@shared/models/expert-advisor.ts';
import { ExpertParameterName } from '@shared/models/expert-parameter-name.ts';

export function getParameters(expert: ExpertAdvisor): ExpertParameterName[] {
  return EXPERT_PARAMETER_DEFINITIONS[expert];
}

const COMMON_PARAMETERS: ExpertParameterName[] = [
  'Inversion',
  'Base_Unit',
  'ATR_Period',
  'TP_Distance',
  'SL_Ratio',
  'Break_Even_In_Percent',
  'TS_Start_In_Percent',
  'TS_Distance',
  'TS_Step',
  'SL_Move',
  'Distance_Between_Orders',
  'Distance_Between_Orders_Factor',
  'Trade_Direction',
  'Ini_Lot_Size_For_10k',
  'Use_Fixed_Lot_Size',
  'Ini_Risk_In_Percent',
  'Fixed_Grid_Size',
  'Recovery_Factor',
  'Grid_Recovery_Factor',
  'Grid_Recovery_Factor_Modifier',
  'Grid_Lot_Sum',
  'Grid_Special_Reaction',
  'Grid_Pause_Until_GSR',
  'Grid_Lot_Boost_On_GSR',
  'Grid_Result_Boost_On_GSR',
  'Smart_Loss_Management_On_DD',
  'Smart_Loss_Management_Mode',
  'Smart_Account_Protection_On_DD',
  'Close_All_Orders_On_DD',
  'Close_All_Orders_When_Profit_In_Percent',
  'Close_On_Common_TP',
  'Use_Common_SL',
  'Ajust_First_TP',
  'Min_TP_Move_In_Point',
  'Max_Risk_In_Percent',
  'Max_Lot_Size_For_10k',
  'Max_Opened_Orders_By_EA_Per_Size',
  'Max_Opened_Orders_By_EA',
  'Max_Opened_Orders',
  'Max_Symbols_In_Same_Time',
  'Max_Daily_DD_In_Percent',
  'Max_Daily_Loss',
  'Max_Daily_Profit_In_Percent',
  'Restart_Hour',
  'Old_Orders_Close_On_DD',
  'Max_Equity_Stop',
  'Min_Equity_Stop',
  'EA_Max_Win',
  'EA_Max_Loss',
  'EA_Monthly_Max_Win',
  'Trade_Max_Profit_In_Percent',
  'Trade_Max_Loss_In_Percent',
  'Slippage',
  'Max_Hours_Before_Break_Even',
  'Max_Hours_Before_Closing',
  'Min_Hours_Between_Trade',
  'Min_Hours_After_Loss',
  'Pause_Orders_On_Friday',
  'Pausing_Hour',
  'Close_Orders_On_Friday',
  'Closing_Hour',
  'Apply_Hour_Filter',
  'Start',
  'Stop',
  'Apply_Hour_Filter_Action',
  'Trade_Monday',
  'Trade_Tuesday',
  'Trade_Wednesday',
  'Trade_Thursday',
  'Trade_Friday',
  'Trade_Saturday',
  'Trade_Sunday',
  'GMT_Zone',
  'ATR_Max_Research',
  'Pause_On_High_Volatity_In_Candles',
  'Max_Amount_Of_First_Entries',
];

export const OTHER_PARAMETERS: ExpertParameterName[] = [
  'Non_Trading_DD',
  'Stop_EA',
  'Force_Buy_Word',
  'Force_Sell_Word',
  'Force_Pause_Word',
  'Force_Non_Trading_If_Nothing_Word',
];

const EXPERT_PARAMETER_DEFINITIONS: Record<ExpertAdvisor, ExpertParameterName[]> = {
  candleSuite: ['Suite', 'Extreme_Research', ...COMMON_PARAMETERS],

  rsiBreak: ['Extreme_Research', 'RSI_Period', 'RSI_Start', 'Delta_RSI_Buy', ...COMMON_PARAMETERS],

  emaBb: ['EMA_Slow_Period', 'BB_Period', 'BB_Deviation', 'BB_Way', ...COMMON_PARAMETERS],

  ichimoku: ['Tenkan_Sen', 'Kijun_Sen', 'Senkou_Span_B', 'Sup_Trend', ...COMMON_PARAMETERS],

  strategyCreator: [
    'MA_Slow_Period',
    'MA_Fast_Period',
    'MA_Method',
    'MA_TF',
    'MA_Score',
    'MA_Change_Score',
    'MA_Trend_Period',
    'MA_Trend_Method',
    'MA_Trend_TF',
    'MA_Trend_Score',
    'MA_Trend_Change_Score',

    'RSI_Period',
    'RSI_TF',
    'RSI_Min_Level',
    'RSI_Min_Score',
    'RSI_Min_Change_Score',
    'RSI_Max_Level',
    'RSI_Max_Score',
    'RSI_Max_Change_Score',

    'Tenkan_Sen',
    'Kijun_Sen',
    'Senkou_Span_B',
    'Ichi_TF',
    'Ichi_Cloud_Pos_Score',
    'Ichi_Cloud_Pos_Change_Score',
    'Ichi_Cloud_Way_Score',
    'Ichi_Cloud_Way_Change_Score',
    'Ichi_Tenkan_vs_Kijun_Score',
    'Ichi_Tenkan_vs_Kijun_Change_Score',
    'Ichi_Kijun_vs_Cloud_Score',
    'Ichi_Chiku_vs_All_Score',

    'Engulfing_Candle_Score',

    'BB_Period',
    'BB_Deviation',
    'BB_TF',
    'Under_Lower_BB_Score',
    'Under_Lower_BB_Change_Score',
    'Above_Upper_BB_Score',
    'Above_Upper_BB_Change_Score',
    'Under_Upper_BB_Score',
    'Under_Upper_BB_Change_Score',
    'Above_Lower_BB_Score',
    'Above_Lower_BB_Change_Score',

    'SAR_Step',
    'SAR_Max',
    'SAR_TF',
    'SAR_Score',
    'SAR_Change_Score',

    'Stoch_K_Period',
    'Stoch_D_Period',
    'Stoch_Slowing',
    'Stoch_Average_Methode',
    'Stoch_TF',
    'Stoch_Way_Score',
    'Stoch_Way_Change_Score',
    'Stoch_Min_Level',
    'Stoch_Min_Level_Score',
    'Stoch_Max_Level',
    'Stoch_Max_Level_Score',

    'MACD_TF',
    'MACD_Fast',
    'MACD_Slow',
    'MACD_Signal',
    'MACD_Way_Score',
    'MACD_Way_Change_Score',
    'MACD_Min_Level',
    'MACD_Min_Level_Score',
    'MACD_Max_Level',
    'MACD_Max_Level_Score',

    'Aleatory_Score',
    'Aleatory_Frequency_In_Percent',
    'Aleatory_TP_Variation_In_Percent',
    'Aleatory_SL_Variation_In_Percent',
    'Aleatory_Ini_Lot_For_10k_Variation_In_Percent',
    'Aleatory_Max_Daily_Profit_In_Percent_Variation_In_Percent',
    'Aleatory_Trade_Max_Profit_In_Percent_Variation_In_Percent',

    'Min_Buy_Score',
    'Close_Score',

    'Use_Open_Hour1',
    'Open_Hour1',
    'Use_Open_Hour2',
    'Open_Hour2',
    'Use_Close_Hour',
    'Close_Hour',

    ...COMMON_PARAMETERS,
  ],

  autoBot: [
    'Trade_Direction',
    'Entry_Agressivity',
    'Win_Level',
    'Win_Factor',
    'Recovery_Level',
    'Recovery_Factor',
    'Max_Lot_Size_Vs_Ini',
    'Min_Distance_Between_Entries',
    'Max_Amount_Of_First_Entries',
    'Ini_Lot_Size_For_1k',
    'Adapt_Lot_Size_To_Capital',
  ],
};
